[package]
name = "ykstackmaps"
version = "0.1.0"
authors = ["Edd Barrett <vext01@gmail.com>"]

[dependencies]
elf = { path = "/Users/ledusou/Documents/Repositories/misc/rust-elf", version = "*" }
byteorder = "1.2"
mach_object = "0.1"
